name       : perl-package-deprecationmanager
version    : 0.17
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Package-DeprecationManager-0.17.tar.gz : 1d743ada482b5c9871d894966e87d4c20edc96931bb949fb2638b000ddd6684b
license    : Artistic-2.0
component  : programming.perl
summary    : Manage deprecation warnings for your distribution
description: |
    Manage deprecation warnings for your distribution
rundeps:
    - perl-sub-install
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
